project:
  type: website
  output-dir: docs
  render:
    - "!summary_report.qmd"

website:
  title: "Data Analysis - Research Reports"
  description: >
    Course Projects for STA 9750 at Baruch College
  site-url: "https://RaulSolaNavarro.github.io/STA9750-2026-SPRING/"
  open-graph: true
  navbar:
    background: primary
    search: false

format:
  html:
    theme: litera
    toc: false

editor:
  mode: source
